
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: My little projects
author: Laz
e-mail: tlaszlol@gmail.com
description: This is my static website for my little projects and thei description.

